name: Check PR merge status

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check if code is merged with main branch
        run: |
          git fetch origin main
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [ $(git rev-list --count $BRANCH..origin/main) -eq 0 ]; then
            echo "Code is merged with main branch"
          else
            echo "Code is not merged with main branch"
            exit 1
          fi
